Include auction assets
blend-capital/blend-contracts-v2 pull request #19
Opened 2024-12-25 15:26 UTC by mootz12

* allow auction creates the ability to specify bid and lot assets in an auction
* add protections against potential misuse of assets to create weird / incomplete liquidations

2024-12-27 01:05 UTC, Ryang-21 requested changes

2024-12-27 01:05 UTC, Ryang-21 commented on pool/src/auctions/bad_debt_auction.rs
> +    if user.clone() != backstop {
ditto

2024-12-27 01:05 UTC, Ryang-21 commented on pool/src/auctions/user_liquidation_auction.rs
> +    if user_clone == e.current_contract_address() || user_clone == storage::get_backstop(e) {
ditto

2024-12-27 14:03 UTC, mootz12 commented on pool/src/auctions/auction.rs
>      }
`AuctionType::from_u32(e, auction_type)`

will panic if it is not a valid auction type, so no default case applies, but I should probably ensure that it unit tested appropriately

2024-12-27 14:04 UTC, mootz12 commented on pool/src/auctions/backstop_interest_auction.rs
> +    bid: &Vec<Address>,
it's required for user liquidation auctions, so for consistency it's used for creating all auctions

2024-12-27 17:51 UTC, markuspluna approved these changes
lgtm

2024-12-30 05:53 UTC, Ryang-21 approved these changes

2024-12-30 13:57 UTC, merged